Apps-819 Subject for invoice payment
snabble/snabble-ios-sdk pull request #258
Opened 2023-07-03 11:01 UTC by utilem

Added view to input subject for invoice payment.

See screenshots / comments: 
https://snabble.atlassian.net/browse/APPS-819

2023-07-03 11:40 UTC, mrgrauel requested changes
Nur die Changelog ist falsch.

2023-07-03 11:40 UTC, mrgrauel commented on CHANGELOG.md
> +* Added view to input subject for invoice payment #APPS-819
Du musst eine neue Version erzeugen. Die Version 0.36.0 ist bereits veröffentlicht.

2023-07-04 07:10 UTC, utilem commented on CHANGELOG.md
> +* Added view to input subject for invoice payment #APPS-819
02f9daee0159bb34f5a0e94040266d0e5988489f

2023-07-04 08:14 UTC, mrgrauel requested changes
Bin mir unsicher ob die Änderungen mit der Biometrischen Abfrage gewollt ist und beim der Anpassung mit dem Subject wurde scheinbar vergessen die PaymentMethod zu prüfen.

2023-07-04 08:14 UTC, mrgrauel commented on Sources/UI/Payment/PaymentMethod+Start.swift
> +        self.requestBiometricAuthentication(on: presenter, reason: Asset.localizedString(forKey: "Snabble.Payment.ExternalBilling.title"), completionHandler)
Warum hast du den BiometricAuthentication Request hinzugefügt? Er war vorher bei `externalBilling` nicht vorhanden. Gibt es neue Anforderungen? Im Ticket habe ich dazu nichts gefunden.

2023-07-04 08:14 UTC, mrgrauel commented on Sources/Core/Cart/CheckoutRequests.swift
> +                }
Ich habe mit 4076217e0a6b03bba034f0489aced3a37b998eae noch ein Check für die Payment Methode hinzugefügt. Wir hatten doch gesagt das wir die Kombination prüfen. Macht Android es nicht oder warum hast du nur auf den OriginType geprüft?

2023-07-04 08:50 UTC, mrgrauel approved these changes

2023-07-04 08:59 UTC, merged