Apps-890 Update SwiftUI map view for public usage
snabble/snabble-ios-sdk pull request #259
Opened 2023-07-05 13:48 UTC by utilem

Der vorherige Ansatz das Map Binding für die aktuelle Region über das Konstrukt `Binding{ get: { return region  }, set {_ in }`  zu lösen, funktioniert mit der aktuellen SwiftUI Version nicht. Der Code `.onChange(of: mode) { _ in  currentRegion = region }` löst dieses Problem.

Zusätzlich erfolgt der Updated der distances (und damit ein Redraw des Map Views) erst nach einer Bewegung von min. 20 Metern.

https://snabble.atlassian.net/browse/APPS-890

2023-07-05 14:20 UTC, mrgrauel requested changes
Wenn die Map bewege flackert nun das Icon des Shops, das war vorher nicht der Fall. Wird es immer wieder neugezeichnet? Können wir das verhindern?

2023-07-05 17:41 UTC, utilem commented on Sources/UI/ShopFinder/Model/ShopsViewModel.swift
> +        }
Als User (und Entwickler) finde ich es sehr verwirrend, wenn sich die Markierung meiner Position permanent neu zeichnet (Flickern des Pin-Symbols), ohne dass ich mich wesentlich bewege.

2023-07-06 05:27 UTC, mrgrauel commented on Sources/UI/ShopFinder/Model/ShopsViewModel.swift
> +        }
Ist es mit @snabble/android und @jwillius abgesprochen? Wir sollten klären, ob Android es auch umsetzt oder ob wir hier bewusst ein anderes Verhalten wollen.

2023-07-06 10:14 UTC, utilem commented on Sources/UI/ShopFinder/Model/ShopsViewModel.swift
> +        }
ist nun wieder rausgenommen

1b6597876114eda68dd81a82be6050f6b3e52c85

2023-07-06 10:20 UTC, utilem commented on CHANGELOG.md
> +* Make map view available for navigation in hosting apps #APPS-890
85e85ce4ce49b848d273f01474a92aacb321b508

2023-07-06 10:26 UTC, utilem commented
> Wenn ich die Map bewege flackert nun das Icon des Shops, das war vorher nicht der Fall. Wird es immer wieder neugezeichnet? Können wir das verhindern?

Nun flackert es nicht mehr

2023-07-11 07:44 UTC, merged