Badge bei neuem Kassenbon in der Tab-Bar
snabble/snabble-ios-sdk pull request #277
Opened 2023-10-30 13:09 UTC by utilem

Das ist ein etwas größerer PR geworden, da ich die Kassenbonliste auf SwiftUI umgestellt habe.

Zusätzlich habe ich die Sample-App im SDK angepasst:

- System Images für die TabBar Icons (wie in teo)
- Kassenbons als TabBar Item hinzugefügt
- "Scanner" TabBar heisst jetzt "Einkaufen"

Getestet habe ich den branch mit Sample, Snabble und teo-App.
https://snabble.atlassian.net/browse/APPS-1108

### Definition of Done
- [ ] Anforderungen erfüllt
- [ ] Deployment Target
- [ ] Home-Button vs. Face-ID Device (SafeArea Guides)
- [ ] Dark / Light Mode
- [ ] Product Owner Review

2023-10-31 10:46 UTC, mrgrauel requested changes
Der ungelesen und gelesen Status ist nicht wie im Ticket definiert.

<img width="708" alt="image" src="https://github.com/snabble/snabble-ios-sdk/assets/148758/20ff0213-c406-4fd7-89a3-9908d7e51013">

2023-10-31 10:46 UTC, mrgrauel commented on Sources/UI/DynamicView/WidgetPurchasesView.swift
> +    }
Hast du es vergessen zu entfernen?

2023-10-31 10:55 UTC, mrgrauel commented
@utilem scheinbar hast du undefinierte Anforderungen umgesetzt. Lass uns bitte bei dem Ticket bleiben und nur das geforderte Verhalten umsetzen. Siehe [Ticket](https://snabble.atlassian.net/browse/APPS-1011) und [Slack](https://snabble.slack.com/archives/C06078ATBBN/p1698749012606439)

2023-10-31 10:56 UTC, mrgrauel commented
> Der ungelesen und gelesen Status ist nicht wie im Ticket definiert.
> 
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/148758/279348153-20ff0213-c406-4fd7-89a3-9908d7e51013.png">



> Der ungelesen und gelesen Status ist nicht wie im Ticket definiert.
> 
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/148758/279348153-20ff0213-c406-4fd7-89a3-9908d7e51013.png">

Die Anmerkung ist hinfällig, da es noch nicht gewollt ist.

2023-10-31 12:36 UTC, utilem commented on Sources/UI/DynamicView/WidgetPurchasesView.swift
> +    }
7a6aee99501ed6c4fcd39857de4d5f7d3a8c28ab

2023-11-02 07:39 UTC, mrgrauel requested changes
Der Badge wird nicht erst entfernt wenn der Kassenbon Tab aufgerufen wird.

Jedesmal wenn die Kassenbons geladen werden, wird der Badge zurückgesetzt. Beispielsweise wenn ich die App schließe mit aktivem Batch und erneut öffne ist der Badge weg. Anforderung ist das der Badge verschwindet wenn der Kassenbon Tab aufgerufen wird.

> Das Badge bleibt so lange aktiv, bis die Kassenbon-Liste aufgerufen wurde.

https://snabble.atlassian.net/browse/APPS-1011

2023-11-03 08:54 UTC, utilem commented
> Der Badge wird nicht erst entfernt wenn der Kassenbon Tab aufgerufen wird.
> 
> Jedesmal wenn die Kassenbons geladen werden, wird der Badge zurückgesetzt. Beispielsweise wenn ich die App schließe mit aktivem Batch und erneut öffne ist der Badge weg. Anforderung ist das der Badge verschwindet wenn der Kassenbon Tab aufgerufen wird.
> 
> > Das Badge bleibt so lange aktiv, bis die Kassenbon-Liste aufgerufen wurde.
> 
> https://snabble.atlassian.net/browse/APPS-1011

25b07e44e8514a33813e36f5d2dd0f4d65c70f8f

2023-11-03 11:41 UTC, mrgrauel commented on Sources/UI/Receipts/ReceiptsListViewController.swift
> +        UIApplication.shared.applicationIconBadgeNumber = unloaded
Die Anforderung gibt es nicht. Warum willst du ein Badge auf dem App Icon anzeigen?

2023-11-03 12:00 UTC, utilem commented on Sources/UI/Receipts/ReceiptsListViewController.swift
> +        UIApplication.shared.applicationIconBadgeNumber = unloaded
66c659226b744bd0c9913cc9155ca65c619d950f

2023-11-06 13:16 UTC, mrgrauel requested changes
Wir haben Themen im Huddle besprochen.

2023-11-07 10:34 UTC, utilem commented
> Wir haben Themen im Huddle besprochen.

Mit dem commit 95d30031a114607cb196cec61654108fad10cbb9  habe ich die Änderungen eingearbeitet. Jetzt habe ich das Problem, dass die letzten Kassenbons auf dem Homescreen, nicht angezeigt werden. Es wird zwar die OrderList geladen, aber die entsprechende completion wird für das WidgetPurchasesView wird nicht aufgerufen. 
Meine Vermutung ist, das die entsprechende Instanz nicht mehr existiert. Die init-Methode von WidgetPurchasesView wird zweimal aufgerufen, es werden zwei LastPurchasesViewModel instanziiert, die OrderList wird von der ersten Instanz geladen und zwischendurch durch die zweite Instanz in WidgetPurchasesView init() ersetzt.

2023-11-13 10:40 UTC, mrgrauel requested changes
Ich habe leider weiterhin den Fall das beim initialen Starten die Kassenbons nicht geladen werden.

Durch den anstehenden Teo Release habe ich nicht genau geprüft warum, das würde ich falls du es nicht findest noch genauer debuggen.

2023-11-13 10:40 UTC, mrgrauel commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +        synchronize()
Das ist nicht mehr notwendig.

https://developer.apple.com/documentation/foundation/userdefaults/1414005-synchronize

2023-11-13 10:40 UTC, mrgrauel commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +    private(set) var projectId: Identifier<Project>
Das kann eine Konstante `let` sein.

2023-11-13 10:40 UTC, mrgrauel commented on Sources/Core/Orders/OrderList.swift
> +    public func cachedReceiptURL(_ project: Project) -> URL {
`Project` wird hier nicht benötigt.

2023-11-13 10:40 UTC, mrgrauel commented on Sources/Core/Orders/OrderList.swift
> +    public func hasCachedReceipt(_ project: Project) -> Bool {
`Project` wird hier nicht benötigt.

2023-11-13 10:40 UTC, mrgrauel commented on Sources/Core/Orders/OrderList.swift
> +    }
Die Methode wird nicht benötigt.

2023-11-13 10:40 UTC, mrgrauel commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +    }
Wofür verwendest du diese Variable? Nach meinem Verständnis ist diese Information nicht notwendig.

2023-11-14 08:40 UTC, utilem commented on Sources/Core/Orders/OrderList.swift
> +    public func cachedReceiptURL(_ project: Project) -> URL {
f94a55d5b80a7492d78baf32ff5b96ad2e0407e3

2023-11-14 08:40 UTC, utilem commented on Sources/Core/Orders/OrderList.swift
> +    public func hasCachedReceipt(_ project: Project) -> Bool {
f94a55d5b80a7492d78baf32ff5b96ad2e0407e3

2023-11-14 08:40 UTC, utilem commented on Sources/Core/Orders/OrderList.swift
> +    }
f94a55d5b80a7492d78baf32ff5b96ad2e0407e3

2023-11-14 08:45 UTC, utilem commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +    private(set) var projectId: Identifier<Project>
2d191a48bc6b332e9f7c9d879261d24749f6f070

2023-11-14 08:45 UTC, utilem commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +    }
2d191a48bc6b332e9f7c9d879261d24749f6f070

2023-11-20 08:47 UTC, mrgrauel requested changes

2023-11-20 08:47 UTC, mrgrauel commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +                load()
Müssen wir hier nicht den `state` noch auf `idle` zurücksetzen?

2023-11-20 08:47 UTC, mrgrauel commented on Sources/UI/Receipts/LastPurchasesViewModel.swift
> +        didSet {
Müssen wir hier nicht auch `imageCache` und `numberOfUnloaded` zurücksetzen?

2023-11-20 13:10 UTC, mrgrauel submitted a review, later dismissed
Bitte prüfe nochmal, aber sollte nun passen.

Wie besprochen habe ich auf der gesamten Liste die Abhängigkeit zum Projekt entfernt.

2023-11-20 15:13 UTC, utilem commented
> Bitte prüfe nochmal, aber sollte nun passen.
> 
> Wie besprochen habe ich auf der gesamten Liste die Abhängigkeit zum Projekt entfernt.

Das sieht so schon sehr viel besser aus. Allerdings habe ich bei einer frischen Installation (Simulator) der App nach dem ersten Einkauf kein Badge und keine Anzeige auf dem Dashboard gesehen.

2023-11-20 15:29 UTC, mrgrauel commented
@utilem good catch. Fixed with f3a7efbf1cf7651c6a36d84b85949ed914124a62

2023-11-20 15:31 UTC, mrgrauel approved these changes

2023-11-21 12:12 UTC, mrgrauel submitted a review, later dismissed
Wir haben durch die Notifications `snabbleCardUpdated` ein Hinweis, aber der hinweis kommt manchmal so schnell das wir vom Server noch keine Information über ein neuen Kassenbon erhalten, wodurch es in Zwischenfällen zu fehlenden Badges kommen kann.

2023-11-22 08:06 UTC, mrgrauel approved these changes

2023-11-22 15:34 UTC, utilem commented
Nach einer frischen Installation und dem ersten Einkauf, erhalte ich nach Bestätigen des Checkout-Screens einen Badge am Kassenbon TabBar-Item, der Home-Screen zeigt mir diesen Einkauf jedoch nicht an.

![Simulator Screenshot - iPhone 15 Pro - 2023-11-22 at 16 30 58](https://github.com/snabble/snabble-ios-sdk/assets/45751166/4c9b2fd0-358f-4b40-84e3-88e909372c32)

2023-11-23 08:01 UTC, mrgrauel commented
Vermutlich der bekannte Fehler, das der eine Refresh zu früh kommt bevor der kassenbon angelegt ist? 🤔

2023-11-23 10:23 UTC, utilem commented
> Vermutlich der bekannte Fehler, das der eine Refresh zu früh kommt bevor der kassenbon angelegt ist? 🤔

Ja, das wird wohl so sein, ich habe nochmals debugged und die OrderList.load() wird korrekt aufgerufen.

2023-11-23 10:25 UTC, merged