add unread badge to receipts line items
snabble/snabble-ios-sdk pull request #285
Opened 2023-12-04 12:20 UTC by utilem

https://snabble.atlassian.net/browse/APPS-1023

### Definition of Done
- [x] Anforderungen erfüllt
- [x] Deployment Target
- [x] Home-Button vs. Face-ID Device (SafeArea Guides)
- [x] Dark / Light Mode
- [x] Product Owner Review

2023-12-04 12:30 UTC, mrgrauel requested changes
> Put data cache files in the Library/Caches/ directory. Cache data can be used for any data that needs to persist longer than temporary data, but not as long as a support file. Generally speaking, the application does not require cache data to operate properly, but it can use cache data to improve performance. Examples of cache data include (but are not limited to) database cache files and transient, downloadable content. Note that the system may delete the Caches/ directory to free up disk space, so your app must be able to re-create or download these files as needed.

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

Wir sollten nicht `.cachesDirectory` für eine Persistierung in der App verwenden, da das System alle Daten in dem Ordner löschen könnte wenn der Speicherplatz benötigt wird.

Sollte ich es richtig verstehen sollten wir den Application Support Ordner verwenden.

2023-12-06 10:48 UTC, utilem commented
> > Put data cache files in the Library/Caches/ directory. Cache data can be used for any data that needs to persist longer than temporary data, but not as long as a support file. Generally speaking, the application does not require cache data to operate properly, but it can use cache data to improve performance. Examples of cache data include (but are not limited to) database cache files and transient, downloadable content. Note that the system may delete the Caches/ directory to free up disk space, so your app must be able to re-create or download these files as needed.
> 
> https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html
> 
> Wir sollten nicht `.cachesDirectory` für eine Persistierung in der App verwenden, da das System alle Daten in dem Ordner löschen könnte wenn der Speicherplatz benötigt wird.
> 
> Sollte ich es richtig verstehen sollten wir den Application Support Ordner verwenden.

c3d203a6cb4da31dde08885d4752624c6cbc0fae

2023-12-06 10:52 UTC, mrgrauel requested changes
Merge Konflikte und das Naming der Methoden `cache` passen durch die Anpassung des Ordners nicht mehr, da die Kassenbons nicht gecached sind.

2023-12-06 15:13 UTC, mrgrauel requested changes
Der Abstand nach Links passt nicht mit dem Design. Der Badge soll nicht die Einrückung komplett anpassen, sondern innerhalb der Einrückung angezeigt werden. 
![image](https://github.com/snabble/snabble-ios-sdk/assets/148758/c5ecec67-255c-49fc-bf71-50c7c79dd169)


![image](https://github.com/snabble/snabble-ios-sdk/assets/148758/632b18e6-f76b-4afd-9068-45193ce44e44)

2023-12-07 12:59 UTC, merged