Giropay integration
snabble/snabble-ios-sdk pull request #297
Opened 2024-02-14 11:25 UTC by utilem

Added some shop related payment validation methods.

https://snabble.atlassian.net/browse/APPS-1342

Please test with teo branch apps-1342

### Definition of Done
- [x] Anforderungen erfüllt
- [x] Deployment Target
- [x] Home-Button vs. Face-ID Device (SafeArea Guides)
- [x] Dark / Light Mode
- [x] Product Owner Review

2024-02-14 15:06 UTC, mrgrauel reviewed
@utilem 
1. könntest du bisschen mehr Kontext geben? Mir ist nicht klar was ich Review soll. 
2. Was sind die Anforderung der Anpassungen?
3. Warum hast du die License Informationen entfernt?

2024-02-15 07:11 UTC, utilem commented
> 1. könntest du bisschen mehr Kontext geben? Mir ist nicht klar was ich Review soll.
> 2. Was sind die Anforderung der Anpassungen?
In der Parent-Story sollte eigentlich alles drinstehen: https://snabble.atlassian.net/browse/APPS-1327
> 3. Warum hast du die License Informationen entfernt?
Das kann ich mir nicht erklären, ich habe dort eigentlich gar nichts geändert.

2024-02-15 08:47 UTC, mrgrauel requested changes
Nach Rücksprache mit @Fabtron und @J-Rocke werden wir es von Blacklisting auf Whitelisting umstellen.

2024-02-15 10:34 UTC, mrgrauel approved these changes

2024-02-15 10:45 UTC, merged