Shopping cart displays wrong discounted prices #APPS-1658
snabble/snabble-ios-sdk pull request #341
Opened 2024-07-03 07:34 UTC by utilem

Use `units` instead of `amount` to calculate correct discount.

https://snabble.atlassian.net/browse/APPS-1658

2024-07-04 07:17 UTC, g-w requested changes

2024-07-04 07:17 UTC, g-w commented on UI/Sources/ShoppingCart/Models/ShoppingCartViewModel.swift
> +                let discountCartItem = ShoppingCartItemDiscount(discount: (lineItem.units ?? lineItem.amount) * modifier.price, name: modifier.name, type: .priceModifier)
Grundsätzlich kann es natürlich auch manual discounts für gewogene Ware geben.

Evtl. wäre es sinnvoll eine Methode `quantity()` auf dem Line Item zu haben, die dann immer verwendet wird?

2024-07-04 07:17 UTC, g-w commented on UI/Sources/ShoppingCart/Models/ShoppingCartViewModel.swift
> +                let discountCartItem = ShoppingCartItemDiscount(discount: (lineItem.units ?? lineItem.amount) * modifier.price, name: modifier.name, type: .priceModifier)
Dafür sollte es einen Test geben.

2024-07-04 07:23 UTC, utilem commented on UI/Sources/ShoppingCart/Models/ShoppingCartViewModel.swift
> +                let discountCartItem = ShoppingCartItemDiscount(discount: (lineItem.units ?? lineItem.amount) * modifier.price, name: modifier.name, type: .priceModifier)
So sieht es bei Wiegeware aus:
![IMG_5510](https://github.com/snabble/snabble-ios-sdk/assets/45751166/74ba4bde-3aba-4952-a359-c80774f0b7f0)

2024-07-05 05:28 UTC, utilem commented on UI/Sources/ShoppingCart/Models/ShoppingCartViewModel.swift
> +                let discountCartItem = ShoppingCartItemDiscount(discount: (lineItem.units ?? lineItem.amount) * modifier.price, name: modifier.name, type: .priceModifier)
> Grundsätzlich kann es natürlich auch manual discounts für gewogene Ware geben.
> 
> Evtl. wäre es sinnvoll eine Methode `quantity()` auf dem Line Item zu haben, die dann immer verwendet wird?

https://github.com/snabble/snabble-ios-sdk/pull/341/commits/4f1dfaa54c7da18a8c48005e9ac8466df92d627e

2024-07-09 08:51 UTC, g-w approved these changes

2024-07-09 09:34 UTC, merged