Scanner interpretiert Code auf Leergutbon #APPS-1642
snabble/snabble-ios-sdk pull request #414
Opened 2024-12-10 13:01 UTC by utilem

https://snabble.atlassian.net/browse/APPS-1642

2025-01-08 10:22 UTC, mrgrauel reviewed
@utilem ich warte noch auf deinen Fix mit dem leeren Warenkorb. An sich ist der Sourcecode ausreichend.

2025-01-08 10:22 UTC, mrgrauel commented on UI/Sources/ShoppingCart/Models/ShoppingCart+Vouchers.swift
> +    }
Kleinigkeit, aber hier würde ich empfehlen das wir den `unknown` Case hier abfragen, da wir ansonsten bei einem neuen Type keine Fehlermeldung erhalten.

```suggestion
    var name: String {
        switch self {
        case .depositReturn:
            return Asset.localizedString(forKey: "Snabble.ShoppingCart.DepositReturn.title")
        case .unknown:
            return ""
        }
    }
```

2025-01-08 17:02 UTC, utilem commented on UI/Sources/ShoppingCart/Models/ShoppingCart+Vouchers.swift
> +    }
https://github.com/snabble/snabble-ios-sdk/pull/414/commits/bf4766e0eb70137e6d5a3cad5d0f43ed2a4b7088

2025-01-08 17:13 UTC, utilem commented
Meine letzen Änderungen sollten das Problem lösen, wenn nur Leergutbons im Warenkorb liegen. Die Prüfung auf einen leeren Warenkorb erfolgt auf `shoppingCart.numberOfItems` und liefert die Anzahle der Produkte (`shoppingCart.items.count`) plus die Anzahl der Vouchers/Leergutbons (`shoppingCart.vouchers.count`).

2025-01-09 10:13 UTC, mrgrauel requested changes
@utilem hast du es getestet? Ich kann nun gar keine Produkte mehr hinzufügen 🤔

2025-01-13 08:55 UTC, utilem commented
@mrgrauel Habe es getestet, bei mir funktioniert es wie erwartet.

2025-01-13 14:23 UTC, mrgrauel approved these changes

2025-01-13 15:01 UTC, merged